#!/usr/bin/env python
# coding: utf-8

# In[8]:


import json

dictPoets = {}

engPoets = open("rekhta_poets_english.tsv","r")

for poet in engPoets:
    poetInfo = poet.split("\t")
    name = poetInfo[0].strip()
    link = poetInfo[1].strip()
    dictPoets[link] = { "english" : name }

engPoets.close()
